<?php
/**
 * CNC Register/Book Space Shortcode - BookMyShow Style (Exact Layout)
 * Features: Tighter Grid, Smart Popups, Status Logic, Mobile Summary
 */

ob_start();

// --------------------------------------------------------------------
// 1. DATA FETCHING: Centralized Data
// --------------------------------------------------------------------

require_once get_stylesheet_directory() . '/inc/floorplan-config.php';
require_once get_stylesheet_directory() . '/inc/floorplan-data.php';
$stalls = cnc_get_floorplan_data();
$grid_rows = CNC_GRID_ROWS;
$grid_cols = CNC_GRID_COLS;

$current_user = wp_get_current_user();
$prefill_company = '';
$prefill_contact = '';
$prefill_phone   = '';
$prefill_email   = '';
if ($current_user && $current_user->ID) {
    $prefill_company = get_user_meta($current_user->ID, 'cnc_company_name', true) ?: $current_user->display_name;
    $prefill_contact = get_user_meta($current_user->ID, 'first_name', true) ?: $current_user->display_name;
    $prefill_phone   = get_user_meta($current_user->ID, 'cnc_phone', true);
    $prefill_email   = $current_user->user_email;
}

// Debug Grid Data
if (empty($stalls)) {
    echo "<!-- DEBUG: No stalls found in cnc_get_floorplan_data() -->";
    error_log("CNC Floorplan: No stalls found.");
} else {
    echo "<!-- DEBUG: Loaded " . count($stalls) . " stalls. -->";
}

// AJAX URL for JS
$ajax_url = admin_url('admin-ajax.php');
?>

<script>
    var cnc_ajax_url = "<?php echo esc_url($ajax_url); ?>";
    var cnc_prefill = <?php echo wp_json_encode([
        'company' => $prefill_company,
        'contact' => $prefill_contact,
        'phone'   => $prefill_phone,
        'email'   => $prefill_email,
    ]); ?>;
</script>

<style>
/* === CONFIGURATION === */
:root {
    --bms-green: <?php echo CNC_COLOR_AVAILABLE; ?>;
    --bms-orange: <?php echo CNC_COLOR_PENDING; ?>;
    --bms-grey: <?php echo CNC_COLOR_BOOKED; ?>;
    --bms-dark: #333;
    --bms-red: <?php echo CNC_COLOR_EXIT; ?>;
    --bms-blue: <?php echo CNC_COLOR_WASHROOM; ?>;
    --grid-gap: <?php echo CNC_GRID_GAP_PX; ?>px;
}

.cnc-booking-wrapper {
    background: #F8F9FA;
    padding: 20px 0 80px; /* Extra bottom padding for mobile bar */
    font-family: 'Inter', sans-serif;
    position: relative;
}

.cnc-booking-container {
    max-width: 1400px;
    margin: 0 auto;
    padding: 0 15px;
    display: flex;
    flex-direction: column;
    gap: 20px;
}

/* MAP CARD */
.cnc-map-card {
    background: #fff;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.05);
    overflow-x: auto; /* Horizontal scroll */
    text-align: center;
}

.cnc-map-legend {
    display: flex;
    justify-content: center;
    gap: 20px;
    margin-bottom: 25px;
    flex-wrap: wrap;
}

.legend-item { display: flex; align-items: center; gap: 6px; font-size: 12px; font-weight: 600; color: #555; }
.legend-dot { width: 14px; height: 14px; border-radius: 3px; }
.legend-dot.green { background: var(--bms-green); }
.legend-dot.orange { background: var(--bms-orange); }
.legend-dot.grey { background: var(--bms-grey); }

/* TIGHT GRID SYSTEM */
.cnc-grid {
    display: grid;
    grid-template-columns: repeat(<?php echo intval($grid_cols); ?>, 1fr);
    grid-template-rows: repeat(<?php echo intval($grid_rows); ?>, 1fr);
    gap: var(--grid-gap); /* CRITICAL: Matches Backend GAP */
    background-color: #f0f0f0; /* Standard Gap Color */
    padding: var(--grid-gap); /* Outer padding matches gap */
    aspect-ratio: <?php echo intval($grid_cols); ?>/<?php echo intval($grid_rows); ?>;
    min-width: 800px;
    overflow: auto;
    border: 1px solid #ccc;
    box-sizing: border-box;
    position: relative; /* For z-index context */
}

/* STALL UNITS */
.stall {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: 10px;
    font-weight: 600;
    cursor: pointer;
    transition: transform 0.1s;
    background: #fff; /* White cells like backend */
    color: #333;
    text-align: center;
    line-height: 1.1;
    position: relative;
    border-radius: 0; /* Sharper edges like backend */
    overflow: hidden;
    padding: 2px;
    box-shadow: none; /* Flat look like backend */
    z-index: 10; /* Above background grid */
}

.stall:hover {
    transform: none; /* No scale on hover for cleaner grid */
    background-color: #f9f9f9;
    z-index: 20;
}

/* Background Grid Cells (Generated by JS) */
.bg-cell {
    background: #fff;
    z-index: 1;
    min-width: 0;
    min-height: 0;
}
.stall::after {
    content: attr(data-id) " - " attr(data-dim);
    position: absolute;
    bottom: 100%;
    left: 50%;
    transform: translateX(-50%);
    background: rgba(0,0,0,0.8);
    color: #fff;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 10px;
    white-space: nowrap;
    opacity: 0;
    pointer-events: none;
    transition: opacity 0.2s;
    z-index: 20;
    margin-bottom: 5px;
}
.stall:hover::after { opacity: 1; }

/* Status Styles */
.status-available { background: var(--bms-green); border: 1px solid #27AE60; }
.status-pending { background: var(--bms-orange); border: 1px solid #D35400; color: #fff; }
.status-booked { background: var(--bms-grey); border: 1px solid #95A5A6; color: #555; cursor: not-allowed; }

/* Feature Styles */
.stall.status-feature { cursor: default; font-size: 9px; display: flex; align-items: center; justify-content: center; text-align: center; box-shadow: none; }
.stall.status-feature:hover { transform: none; box-shadow: none; }
.stall.status-feature::after { display: none; } /* No tooltip */

.type-fire-exit { background: #E74C3C; color: white; border: 1px solid #C0392B; font-weight: bold; }
.type-washroom { background: #3498DB; color: white; border: 1px solid #2980B9; }
.type-service { background: #9B59B6; color: white; border: 1px solid #8E44AD; font-size: 9px; }
.type-entry { background: #F39C12; color: white; border: 1px solid #E67E22; font-weight: 800; font-size: 12px; letter-spacing: 1px; }
.type-exit { background: #E67E22; color: white; border: 1px solid #D35400; font-weight: 800; }
.type-freight-entry { background: #95A5A6; color: white; border: 1px solid #7F8C8D; font-weight: 600; }
.type-stairs { background: #34495E; color: white; border: 1px solid #2C3E50; }
.type-stage { background: #1ABC9C; color: white; border: 1px solid #16A085; font-weight: 700; }
.type-registration { background: #9B59B6; color: white; border: 1px solid #8E44AD; }
.type-lounge { background: #27AE60; color: white; border: 1px solid #1E8449; }
.type-storage { background: #7F8C8D; color: white; border: 1px solid #626567; }
.type-electrical { background: #F1C40F; color: #333; border: 1px solid #D4AC0D; }
.type-pillar { background: #34495E; color: white; border: 1px solid #1C2833; }
.type-corridor { background: #27AE60; color: white; border: 1px solid #1E8449; opacity: 0.7; }
.type-blank { background: #ECF0F1; color: #666; border: 1px solid #BDC3C7; }
.type-custom-area { background: #8E44AD; color: white; border: 1px solid #6C3483; }
.type-feature { background: #FFC107; color: #333; border: 1px solid #F39C12; cursor: default; }
.type-food-court { background: #E74C3C; color: white; border: 1px solid #C0392B; }
.type-networking { background: #2ECC71; color: white; border: 1px solid #27AE60; }

/* Common Area Styles - Non-clickable */
.stall.common-area {
    cursor: default;
    pointer-events: none;
}
.stall.common-area::after { display: none; } /* No tooltip */

/* Text Direction Classes */
.stall .item-label.text-vertical-up {
    writing-mode: vertical-rl;
    text-orientation: mixed;
    transform: rotate(180deg);
}
.stall .item-label.text-vertical-down {
    writing-mode: vertical-rl;
    text-orientation: mixed;
}
.stall .item-label.text-horizontal {
    writing-mode: horizontal-tb;
}

.stall.selected {
    background: var(--bms-dark);
    border-color: #000;
    box-shadow: 0 0 0 2px #fff, 0 0 0 4px var(--bms-dark);
    z-index: 5;
}

/* Areas */
.area-seminar {
    grid-column: 1 / 4; grid-row: 1 / 6;
    background: #f9f9f9; border: 1px dashed #ccc;
    display: flex; align-items: center; justify-content: center;
    color: #999; font-size: 11px; font-weight: bold;
}

/* POPUP / BOTTOM SHEET */
.stall-popup-overlay {
    position: fixed; inset: 0; background: rgba(0,0,0,0.5); z-index: 9999;
    display: none; align-items: flex-end; justify-content: center;
}
.stall-popup-overlay.active { display: flex; animation: fadeIn 0.2s; }

.stall-popup-content {
    background: #fff;
    width: 100%;
    max-width: 500px;
    border-radius: 16px 16px 0 0;
    padding: 25px;
    position: relative;
    box-shadow: 0 -4px 20px rgba(0,0,0,0.2);
    animation: slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

.popup-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 15px; }
.popup-title { margin: 0; font-size: 18px; color: #333; }
.popup-subtitle { color: #666; font-size: 14px; margin-top: 4px; }
.btn-close { background: none; border: none; font-size: 24px; cursor: pointer; color: #999; padding: 0; }

.popup-details { margin-bottom: 20px; background: #f5f5f5; padding: 15px; border-radius: 8px; }
.detail-row { display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 14px; }
.detail-row:last-child { margin-bottom: 0; }
.detail-label { color: #666; }
.detail-value { font-weight: 600; color: #333; }

.popup-actions { text-align: center; }
.btn-action {
    display: block; width: 100%; padding: 14px;
    border-radius: 8px; border: none;
    font-weight: 600; font-size: 15px;
    cursor: pointer; text-decoration: none;
    transition: background 0.2s;
}
.btn-book { background: var(--bms-red); color: white; }
.btn-book:hover { background: #C0392B; }
.btn-profile { background: #34495E; color: white; }
.btn-profile:hover { background: #2C3E50; }

/* Sticky Summary Bar (Floating Island) */
.sticky-summary {
    position: fixed; 
    bottom: 30px; 
    left: 50%; 
    transform: translateX(-50%) translateY(150%); /* Start hidden below */
    width: 90%;
    max-width: 400px;
    background: #fff; 
    border-radius: 5px; /* Pill shape */
    padding: 10px 20px; 
    z-index: 99999; /* High z-index to be above back-to-top */
    display: flex; 
    justify-content: space-between; 
    align-items: center;
    box-shadow: 0 10px 30px rgba(0,0,0,0.2);
    transition: transform 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275); /* Bouncy pop-up */
    border: 1px solid rgba(0,0,0,0.05);
}
.sticky-summary.visible { 
    transform: translateX(-50%) translateY(0); 
}

@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
@keyframes slideUp { from { transform: translateY(100%); } to { transform: translateY(0); } }

@media (min-width: 768px) {
    .stall-popup-overlay { align-items: center; }
    .stall-popup-content { border-radius: 12px; max-width: 400px; }
}
</style>

<div class="cnc-booking-wrapper">
    <div class="cnc-booking-container">
        <!-- Map Section -->
        <div class="cnc-map-card">
            <h2 style="margin:0 0 20px 0;"><?php echo esc_html(get_option('cnc_event_title', 'Hall 3 Floor Plan')); ?></h2>
            
            <?php if(isset($success_msg)) echo "<div style='padding:15px; background:#d4edda; color:green; border-radius:6px; margin-bottom:20px;'>$success_msg</div>"; ?>
            <?php if(isset($error_msg)) echo "<div style='padding:15px; background:#f8d7da; color:red; border-radius:6px; margin-bottom:20px;'>$error_msg</div>"; ?>

            <div class="cnc-grid">
                
                <?php 
                // Common area types (non-clickable)
                $common_area_types = [
                    'fire-exit', 'entry', 'exit', 'freight-entry', 'washroom', 
                    'stairs', 'stage', 'service', 'registration', 'lounge', 
                    'storage', 'electrical', 'pillar', 'corridor', 'blank', 'custom-area',
                    'food-court', 'networking', 'feature'
                ];
                
                foreach($stalls as $s): 
                    $type = isset($s['type']) ? $s['type'] : 'stall';
                    $is_common_area = isset($s['is_common_area']) ? $s['is_common_area'] : in_array($type, $common_area_types);
                    
                    $classes = 'stall status-' . $s['status'];
                    $classes .= ' type-' . $type;
                    if ($is_common_area) {
                        $classes .= ' common-area';
                    }
                    
                    $style = "grid-row: {$s['r']} / span {$s['h']}; grid-column: {$s['c']} / span {$s['w']};";
                    
                    // Custom Color Logic
                    if (!empty($s['custom_color'])) {
                        $style .= " background-color: " . esc_attr($s['custom_color']) . ";";
                        $style .= " border-color: " . esc_attr($s['custom_color']) . ";";
                    }
                    
                    // Text Color
                    if (!empty($s['text_color'])) {
                        $style .= " color: " . esc_attr($s['text_color']) . ";";
                    }
                    
                    // Font Size
                    if (!empty($s['font_size']) && $s['font_size'] !== 'auto') {
                        $style .= " font-size: " . intval($s['font_size']) . "px;";
                    }
                    
                    // Border
                    if (!empty($s['show_border']) && !empty($s['border_color'])) {
                        $style .= " border: 2px solid " . esc_attr($s['border_color']) . ";";
                    } elseif ($is_common_area && empty($s['show_border'])) {
                        $style .= " border: none;";
                    }
                    
                    // Legacy fill/border support
                    if(!empty($s['fill'])) $style .= " background-color: {$s['fill']};";
                    if(!empty($s['border'])) $style .= " border-color: {$s['border']};";
                    
                    // Text Direction Class
                    $text_dir_class = '';
                    if (!empty($s['text_dir']) && $s['text_dir'] !== 'horizontal') {
                        $text_dir_class = 'text-' . $s['text_dir'];
                    }
                    
                    // Display Label
                    $display_label = !empty($s['display_label']) ? $s['display_label'] : str_replace('3.', '', $s['id']);
                ?>
                    <div class="<?php echo $classes; ?>"
                         style="<?php echo $style; ?>"
                         data-id="<?php echo $s['id']; ?>"
                         data-price="<?php echo $s['price']; ?>"
                         data-area="<?php echo $s['area']; ?>"
                         data-dim="<?php echo $s['dim']; ?>"
                         data-status="<?php echo $s['status']; ?>"
                         data-type="<?php echo esc_attr($type); ?>"
                         data-company="<?php echo esc_attr($s['company']); ?>"
                         data-link="<?php echo esc_attr($s['link'] ?? ''); ?>"
                         data-common-area="<?php echo $is_common_area ? '1' : '0'; ?>">
                        <span class="item-label <?php echo $text_dir_class; ?>"><?php echo esc_html($display_label); ?></span>
                        
                        <?php 
                        // Add Green Line Indicator for Available Stalls
                        if ($s['status'] === 'available' && $type === 'stall' && !$is_common_area): ?>
                            <div style="position:absolute; bottom:0; left:0; width:100%; height:3px; background:#27AE60;"></div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                
            </div>
        </div>
    </div>
</div>

<!-- POPUP MODAL -->
<div class="stall-popup-overlay" id="popup-overlay">
    <div class="stall-popup-content">
        <div class="popup-header">
            <div>
                <h3 class="popup-title" id="pop-title">Stall Details</h3>
                <div class="popup-subtitle" id="pop-status">Available</div>
            </div>
            <button class="btn-close" onclick="closePopup()">×</button>
        </div>
        
        <div class="popup-details" id="pop-details-box">
            <!-- Dynamic Content -->
        </div>
        
        <div class="popup-actions" id="pop-actions">
            <!-- Dynamic Buttons -->
        </div>
        
        <!-- Booking Form (Hidden by default) -->
        <form id="booking-form" method="POST" style="display:none; margin-top:20px;">
            <input type="hidden" name="selected_stall_id" id="input_id">
            <input type="hidden" name="cnc_book_stall" value="1">
            <?php wp_nonce_field('cnc_booking_action', 'cnc_booking_nonce'); ?>
            <div style="display:grid; gap:10px; text-align:left;">
                <input type="text" name="company_name" placeholder="Company Name" required style="padding:12px; border:1px solid #ddd; border-radius:6px; width:100%;">
                <input type="text" name="contact_person" placeholder="Contact Person" required style="padding:12px; border:1px solid #ddd; border-radius:6px; width:100%;">
                <input type="tel" name="phone" placeholder="Mobile Number" required style="padding:12px; border:1px solid #ddd; border-radius:6px; width:100%;">
                <input type="email" name="email" placeholder="Email Address" required style="padding:12px; border:1px solid #ddd; border-radius:6px; width:100%;">
                <button type="submit" class="btn-action btn-book">Submit Booking Request</button>
            </div>
        </form>
    </div>
</div>

<!-- STICKY SUMMARY (Mobile) -->
<div class="sticky-summary" id="sticky-summary">
    <div>
        <div style="font-size:12px; color:#666;">Selected</div>
        <strong id="sticky-id" style="font-size:16px; color:#333;">--</strong>
    </div>
    <button id="sticky-btn" class="btn-action btn-book" style="width:auto; padding:10px 25px;" onclick="openBookingForm()">
        Book Now
    </button>
</div>

<script>
const overlay = document.getElementById('popup-overlay');
const detailsBox = document.getElementById('pop-details-box');
const actionBox = document.getElementById('pop-actions');
const bookingForm = document.getElementById('booking-form');
const stickySummary = document.getElementById('sticky-summary');

// GENERATE BACKGROUND GRID (To match Admin Area)
document.addEventListener('DOMContentLoaded', function() {
    const grid = document.querySelector('.cnc-grid');
    if (!grid) return;

    const rows = <?php echo intval($grid_rows); ?>;
    const cols = <?php echo intval($grid_cols); ?>;
    const fragment = document.createDocumentFragment();

    // Create 3000+ empty white cells to form the grid
    for (let r = 1; r <= rows; r++) {
        for (let c = 1; c <= cols; c++) {
            const div = document.createElement('div');
            div.className = 'bg-cell';
            div.style.gridRow = r;
            div.style.gridColumn = c;
            fragment.appendChild(div);
        }
    }
    
    // Insert at the beginning so they sit behind the stalls
    grid.insertBefore(fragment, grid.firstChild);
});

let selectedStalls = new Set();
const prefillFields = () => {
    if (!bookingForm) return;
    const company = bookingForm.querySelector('input[name="company_name"]');
    const contact = bookingForm.querySelector('input[name="contact_person"]');
    const phone   = bookingForm.querySelector('input[name="phone"]');
    const email   = bookingForm.querySelector('input[name="email"]');

    if (company && !company.value && cnc_prefill.company) company.value = cnc_prefill.company;
    if (contact && !contact.value && cnc_prefill.contact) contact.value = cnc_prefill.contact;
    if (phone && !phone.value && cnc_prefill.phone) phone.value = cnc_prefill.phone;
    if (email && !email.value && cnc_prefill.email) email.value = cnc_prefill.email;
};

// Close Modal
function closePopup() {
    overlay.classList.remove('active');
    bookingForm.style.display = 'none';
    actionBox.style.display = 'block';
}

// Open Booking Form inside Modal
function openBookingForm() {
    if(selectedStalls.size === 0) return;
    
    // If modal not open, open it
    if(!overlay.classList.contains('active')) {
        overlay.classList.add('active');
    }
    
    // Show Form
    document.getElementById('pop-title').textContent = 'Book Selected Stalls';
    document.getElementById('pop-status').textContent = selectedStalls.size + ' Stall(s) Selected';
    document.getElementById('pop-status').style.color = '#333';
    
    let html = '<div class="detail-row"><span class="detail-label">Selected IDs:</span> <span class="detail-value">' + Array.from(selectedStalls).join(', ') + '</span></div>';
    detailsBox.innerHTML = html;
    
    actionBox.style.display = 'none';
    bookingForm.style.display = 'block';
    document.getElementById('input_id').value = Array.from(selectedStalls).join(',');
    prefillFields();
}

// Update Sticky Summary
function updateStickySummary() {
    const count = selectedStalls.size;
    const idLabel = document.getElementById('sticky-id');
    const btn = document.getElementById('sticky-btn');
    
    if (count > 0) {
        stickySummary.classList.add('visible');
        idLabel.textContent = count + ' Stall(s) Selected';
        btn.textContent = 'Book ' + count + ' Stall(s)';
    } else {
        stickySummary.classList.remove('visible');
    }
}

// Stall Click Handler
document.querySelectorAll('.stall').forEach(stall => {
    stall.addEventListener('click', function() {
        // DISABLE CLICK FOR COMMON AREAS (Washrooms, Exits, Stairs, etc.)
        if (this.dataset.commonArea === '1') return;
        if (this.dataset.type && this.dataset.type !== 'stall') return;

        const status = this.dataset.status;
        const id = this.dataset.id;

        // Handle Booked/Pending Stalls - Show Details
        if (status === 'booked' || status === 'pending') {
            showStallDetails(this.dataset);
            return;
        }

        // Handle Available Stalls - Toggle Selection
        if (selectedStalls.has(id)) {
            selectedStalls.delete(id);
            this.classList.remove('selected');
        } else {
            selectedStalls.add(id);
            this.classList.add('selected');
        }
        
        updateStickySummary();
    });
});

function showStallDetails(data) {
    document.getElementById('pop-title').textContent = 'Stall ' + data.id;
    
    let html = '';
    let actions = '';
    
    if (data.status === 'booked') {
        // Booked State
        document.getElementById('pop-status').textContent = 'Booked by ' + data.company;
        document.getElementById('pop-status').style.color = '#7F8C8D';
        
        html = `
            <div class="detail-row"><span class="detail-label">Exhibitor:</span> <span class="detail-value">${data.company}</span></div>
            <div class="detail-row"><span class="detail-label">Size:</span> <span class="detail-value">${data.area} Sq.m</span></div>
        `;
        actions = `<a href="${data.link}" class="btn-action btn-profile">View Exhibitor Profile</a>`;
        
    } else {
        // Pending State
        document.getElementById('pop-status').textContent = 'Booking Pending';
        document.getElementById('pop-status').style.color = '#F39C12';
        
        html = `
            <div class="detail-row"><span class="detail-label">Status:</span> <span class="detail-value">Awaiting Approval</span></div>
            <div class="detail-row"><span class="detail-label">Requested By:</span> <span class="detail-value">${data.company}</span></div>
        `;
        actions = `<button class="btn-action" disabled style="background:#eee; color:#999; cursor:not-allowed">Unavailable</button>`;
    }
    
    detailsBox.innerHTML = html;
    actionBox.innerHTML = actions;
    bookingForm.style.display = 'none';
    actionBox.style.display = 'block';
    
    overlay.classList.add('active');
}

// Close on outside click
overlay.addEventListener('click', function(e) {
    if (e.target === overlay) closePopup();
});

// AJAX Form Submission
bookingForm.addEventListener('submit', function(e) {
    e.preventDefault();
    
    const submitBtn = this.querySelector('button[type="submit"]');
    const originalText = submitBtn.textContent;
    submitBtn.disabled = true;
    submitBtn.textContent = 'Submitting...';
    
    const formData = new FormData(this);
    formData.append('action', 'cnc_book_stall');
    
    fetch(cnc_ajax_url, {
        method: 'POST',
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            // Show Success Message in Popup
            document.getElementById('pop-title').textContent = 'Success!';
            document.getElementById('pop-status').textContent = 'Booking Request Submitted';
            document.getElementById('pop-status').style.color = 'green';
            
            detailsBox.innerHTML = `
                <div style="text-align:center; padding:20px;">
                    <div style="font-size:40px; margin-bottom:10px;">✅</div>
                    <p style="color: #0090D9; font-size: 18px; font-weight: 600; margin-bottom: 10px;">
                        Your request for stall(s) ${data.data.booked_stalls.join(', ')} has been submitted!
                    </p>
                    <p style="font-size:12px; color:#666; margin-top:10px;">We will review your request and contact you shortly.</p>
                </div>
            `;
            
            bookingForm.style.display = 'none';
            actionBox.style.display = 'none'; // Hide other actions
            
            // Update UI for booked stalls (turn them orange/pending immediately)
            data.data.booked_stalls.forEach(id => {
                const stall = document.querySelector(`.stall[data-id="${id}"]`);
                if (stall) {
                    stall.classList.remove('status-available');
                    stall.classList.add('status-pending');
                    // Force color update if CSS classes don't handle it immediately due to specificity
                    stall.style.backgroundColor = 'var(--bms-orange)'; 
                    stall.dataset.status = 'pending';
                }
            });
            
            // Clear selection
            selectedStalls.clear();
            updateStickySummary();

            // Redirect if URL provided
            if (data.data.redirect_url) {
                setTimeout(() => {
                    window.location.href = data.data.redirect_url;
                }, 2000); // 2 second delay to read success message
            }
            
        } else {
            alert('Error: ' + (data.data ? data.data.message : 'Unknown error'));
            submitBtn.disabled = false;
            submitBtn.textContent = originalText;
        }
    })
    .catch(error => {
        console.error('Error:', error);
        alert('An error occurred. Please try again.');
        submitBtn.disabled = false;
        submitBtn.textContent = originalText;
    });
});
</script>

<?php
return ob_get_clean();
?>
